
# defalut = 8080
server:
  port: 8080



# logging
logging:
  level:
    org.springframework:  debug


# 다국어 처리
spring:
  messages:
    basename: messages
# 보안
  security:
    user:
      name: username
      password: passw0rd


management:
  endpoints:
    web:
      exposure:
        include: "*"
